version: "3"

services:
  ngrok:
    container_name: ngrok_tunnel
    image: wernight/ngrok
    ports:
      - "4040:4040"
    links:
      - python
    environment:
      - NGROK_AUTH=3fVv5QDD6Wh5jDUg7CtEg_6tsUV7Nz5gy1M6vZA7myF
      - NGROK_PORT=python:5000
      - NGROK_PROTOCOL=http

  nginx:
    container_name: nginx_reverse_proxy
    image: nginx:alpine
    expose:
      - "3000"
    volumes:
      - "./static/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./static:/www/static"
    restart: always

  python:
    container_name: python_api
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - "./app:/usr/src/app"
    restart: always

  postgres:
    container_name: postgres_database
    image: postgres:alpine
    expose:
      - "5432"
    volumes:
      - data-volume:/var/lib/postgresql
    restart: always    


volumes:
  data-volume:
  