FROM python:3-onbuild
MAINTAINER Vikash Kothary <kothary.vikash@gmail.com>
COPY . /usr/src/app
WORKDIR /usr/src/app
# env FLASK_APP=hello.py
# ENTRYPOINT ["flask"]
# CMD ["run"]
ENTRYPOINT ["python"]
CMD ["main.py"]
